CONFIG_DOWNLOAD_DIR = "downloads"
CONFIG_RES_DIR = "resources"
CONFIG_SERVE_DIR = "serve"

CONFIG_GOOGLE_CX = "40230423040234:324234234"
CONFIG_GOOGLE_KEY = "sdfSFDSFfDSfsdf_ASdaSDsd"

CONFIG_DISCORD_TOKEN = "asdASDASDasdaSDasd.aSDASDasD.ASDasdASdASD"
CONFIG_DISCORD_OWNER = "BigBoss#8527"
CONFIG_DISCORD_ME = "FTBot#3537"
CONFIG_DISCORD_MENTION_ME = "<@202194719466455040>"

CONFIG_MY_IP = "127.0.0.1"

CONFIG_DEFAULT_REPLYRATE = 1

# Once a day
CONFIG_MARKOV_TICK_RATING_DEFAULT = 7
CONFIG_MARKOV_TICK_RATING_DAILY_REDUCE = 1
CONFIG_MARKOV_RARE_FILTER = ['nick', 'and', 'for', 'what', 'where', 'when', 'how', 'who', 'now', 'be', 'is', 'or',
                             'the', 'you', 'your', 'we', 'i', 'to', 'too', 'are', 'do', 'don\'t', 'what\'s', 'whats']
CONFIG_MARKOV_RARE_WORD_MIN_LENGTH = 3
CONFIG_MARKOV_CHAIN_ATTEMPTS = 10
CONFIG_MARKOV_VECTOR_LENGTH = 7

CONFIG_MESSAGE_WAKEUP = "Yawn"
CONFIG_MESSAGE_SHUTUP = "ZzZzZzZz"